apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-service-config
  namespace: minecoin
data:
  SERVER_PORT: "8082"
  DB_URL: jdbc:postgresql://postgres:5432/finance_db
  DB_USERNAME: finance_svc
  MAX_OPERATION_AMOUNT: "1000"
  USER_SERVICE_URL: http://user-service:8081
  LOGGING_STRUCTURED_FORMAT_CONSOLE: ecs
